[package]
name = "c51902asm"
version = "0.1.0"
authors = ["Óscar Carrasco <oxcabe@gmail.com>"]
description = "Assembler for the 8-bit c51902 architecture."
edition = "2018"

[dependencies]
clap = "2.33.0"
